// Wallet TYPES
export const SET_NAVIGATION = 'SET_NAVIGATION'
export const SET_ALL_COINS = 'SET_ALL_COINS'
export const SET_PORTFOLIO_COINS = 'SET_PORTFOLIO_COINS'
export const SET_PORTFOLIO_TRANSACTIONS = 'SET_PORTFOLIO_TRANSACTIONS'
export const SET_DATE_TRANSACTION = 'SET_DATE_TRANSACTION'
export const SET_PORTFOLIO_BALANCE = 'SET_PORTFOLIO_BALANCE'

// Storage TYPES
export const CREATE_PASSWORD = 'CREATE_PASSWORD'
export const SET_CURRENT_NETWORK = 'SET_CURRENT_NETWORK'
