// Wallet TYPES
export const SET_NAVIGATION = 'SET_NAVIGATION'
export const SET_ALL_COINS = 'SET_ALL_COINS'
export const SET_PORTFOLIO_COINS = 'SET_PORTFOLIO_COINS'
export const SET_PORTFOLIO_TRANSACTIONS = 'SET_PORTFOLIO_TRANSACTIONS'
export const SET_DATE_TRANSACTION = 'SET_DATE_TRANSACTION'
export const SET_PORTFOLIO_BALANCE = 'SET_PORTFOLIO_BALANCE'
export const SET_PHRASE = 'SET_PHRASE'
export const SET_PRIVATE_KEY = 'SET_PRIVATE_KEY'
export const SET_CHOOSE_COIN = 'SET_CHOOSE_COIN'
export const SET_PORTFOLIO_OPEN = 'SET_PORTFOLIO_OPEN'
export const SET_PORTFOLIO_SORT = 'SET_PORTFOLIO_SORT'

// Storage TYPES
export const CREATE_PASSWORD = 'CREATE_PASSWORD'
export const SET_CURRENT_NETWORK = 'SET_CURRENT_NETWORK'
export const SET_DATA_USER = 'SET_DATA_USER'
export const SET_CURRENT_ACCOUNT = 'SET_CURRENT_ACCOUNT'
